name: Execution Performance

on:
  workflow_dispatch:
    inputs:
      testSuite:
        type: choice
        description: 'Select the test suite to run'
        required: true
        options:
          - pokemonapi.PokemonApiTest
          - taskapi.TaskApiTest
        default: 'taskapi.PokemonApiTest'
      concurrent:
        type: string
        description: 'Quantity of users'
        required: true
        default: '10'

jobs:
  execpokemonapi:
    runs-on: ubuntu-latest
    name: Execution Performance Pokemon API
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DconcurrentUsers=${{ inputs.concurrent }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v4
        with:
          name: gatling report
          path: ./build/reports/gatling
      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v3.7.3
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/gatling
          keep_files: true
          user_name: bhurtado
          user_email: betty.hurtado@gmail.com
          publish_branch: gh_pages
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./pokemonapitest-20240926191634473
  exectaskapi:
    runs-on: ubuntu-latest
    name: Execution Performance Task API
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute test
        run: gradle gatlingRun --simulation=${{ inputs.testSuite }} -DconcurrentUsers=${{ inputs.concurrent }}

      - name: Save report
        if: ${{always()}}
        uses: actions/upload-artifact@v4
        with:
          name: gatling report
          path: ./build/reports/gatling

      - name: "Publish test results"
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/reports/gatling
          keep_files: true
          user_name: bhurtado
          user_email: betty.hurtado@gmail.com
          publish_branch: gh_pages

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./taskapitest-20240926153848148
